language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - pip3 install -r build_requirements.txt
  - pip3 install -r requirements.txt
script:
  - pylint tlnetcard_python --disable=too-few-public-methods,cyclic-import,duplicate-code
